version: "3"
services:
  db:
    image: postgres:12.8
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24